include: package:flutter_lints/flutter.yaml

analyzer:
  plugins: []
  exclude:
    - "build/**"
    - "**/*.g.dart"

linter:
  rules:
    prefer_final_locals: true
    avoid_print: true
    always_use_package_imports: true
    unnecessary_late: true
    use_build_context_synchronously: false
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
